name: gis-conda-rtd-compat
channels:
  - conda-forge
dependencies:
  - python=3.5
  - numpy
  - scipy
  - gdal
  - matplotlib
  - pandas
  - geopandas
  - Pillow
  - netCDF4
  - descartes
  - pyproj
  - cartopy
  - rasterio
  - ipython
  - sphinx
