name: gis-conda-rtd-compat
channels:
  - conda-forge
dependencies:
  - python=3.5
  - numpy=1.12.0
  - scipy=0.18.1
  - geopandas=0.2.1  # let geopandas install mpl, pandas, gdal
  - netCDF4=1.2.7
  - scikit-image=0.12.3
  - cartopy
  - krb5
  - rasterio=1.0a7
  - numpydoc
  - ipython=5.3.0
  - sphinx
