name: gis-conda-rtd-compat
channels:
  - conda-forge
dependencies:
  - python=3.5
  - numpy
  - scipy
  - gdal
  - matplotlib
  - pandas
  - geopandas
  - Pillow=3.0.0  # because RTD installs this version anyway
  - netCDF4
  - descartes
  - pyproj
  - cartopy
  - rasterio
  - ipython
  - sphinx=1.3.5  # because RTD installs this version anyway
